services:
   palworld:
      image: orcist/palworld-server-docker:latest
      restart: unless-stopped
      container_name: palworld-server
      ports:
        - 8211:8211/udp
        - 27015:27015/udp
      environment:
         - PUID=1000
         - PGID=1000
         - PORT=8211 # Optional but recommended
         - PLAYERS=30 # Optional but recommended
         - MULTITHREADING=true
         - RCON_ENABLED=true
         - RCON_PORT=25575
         - ADMIN_PASSWORD="admin"
         - COMMUNITY=true  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
         # Enable the environment variables below if you have COMMUNITY=true
         - SERVER_PASSWORD="password"
         - SERVER_NAME="World of Pals"
         # Configure Savefile Persistence on AWS
         - AWS_S3_BUCKET="s3://<>"
         - AWS_S3_BACKUP_EVERY_SECONDS=600
         - AWS_ACCESS_KEY_ID="<>"
         - AWS_SECRET_ACCESS_KEY="<>"
      # Enable for local mount of the inner container files
      # volumes:
         # - /mnt/d/Projects/palworld-server/Palworld:/palworld/
